version: "3"

services:
  nico:
    image: "nico"
    environment:
      # Additional JVM flags can be passed by providing a whitespace-separated list of flags
      - >
        JAVA_OPTS=
          -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
          -XX:+PrintGC
          -XX:+PrintGCDateStamps
          -XX:+PrintGCTimeStamps
      # In case we key off of being in dev or prod.
      - EXECUTION_ENVIRONMENT=dev
    ports:
      - 5005:5005
      - 8080:8080
      - 8778:8778

  postgres_nico:
    image: postgres
    container_name: postgres_nico
    environment:
      # Fake database credentials to use when doing local development
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=nico
    ports:
      - "5432:5432"
