name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Gradle
      run: ./gradlew :service:dockerBuildImage
      
    - name: Deploy Container
      env:
          DEPLOYER_SERVICE_KEY: ${{ secrets.deployer_service_account }}
      run: |
        echo $DEPLOYER_SERVICE_KEY > temp_secret.json
        gcloud auth activate-service-account github-releaser@nico-264204.iam.gserviceaccount.com --key-file=temp_secret.json --project=nico-264204
        docker tag nico gcr.io/nico-264204/nico-service:latest
        docker push gcr.io/nico-264204/nico-service:latest
        gcloud beta run deploy nico-service --image gcr.io/nico-264204/nico-service:latest --region us-central1 --platform managed
        rm -rf temp_secret.json
